security:
  jwt:
    secret-sey: verysecretkeydonttellanybodyimserious

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://localhost:5432/f1shop
    username: test
    password: test

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false