security:
  jwt:
    secret-sey: verysecretkeydonttellanybodyimserious

spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    url: jdbc:postgresql://postgresql-db:5432/f1shop
    username: f1shop
    password: f1shop348233083

  jpa:
    hibernate:
      ddl-auto: update
    show-sql: false
    open-in-view: false
  sql:
    init:
      mode: always